version: '3'
services:
  python3:
    #restart: always
    build: ./python/
    container_name: 'fundamental_python3'
    tty: true #正常終了させないための仮プロセス
    volumes:
      - ./python/opt:/workdir/opt
    networks:
      fundamental_docker_network:

  postgresql:
    container_name: 'fundamental_postgresql'
    build: ./postgresql/
    ports:
      - 54322:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ginkgo
      POSTGRES_PASSWORD: ginkgo
    #restart: always
    networks:
      fundamental_docker_network:
        ipv4_address: 10.0.1.30

networks: 
  fundamental_docker_network:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 10.0.1.0/24
         gateway: 10.0.1.1